title: Dead Pixel Sec
description: Information Security Community 
author:
  name: "TheBlindHacker"
  email: "deadpixelsec@pm.me"
  url: "www.deadpixelsec.com"

baseurl: "/"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

#Custom Vars
owner: "DeadPixelSec"